version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - POSTGRES_USER=surveyuser
      - POSTGRES_PASSWORD=surveypassword
      - POSTGRES_DB=surveybuilder
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=surveyuser
      - POSTGRES_PASSWORD=surveypassword
      - POSTGRES_DB=surveybuilder
